### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by slremy** [brightmart/text_classification#52]
I'm guessing that this code is intended to be open sourced otherwise it wouldn't be here, but is there a particular license that you'd like to choose for your work?

**Comment by brightmart** [comment]
no particular license yet. you can add one if you like.


________________________________
发件人: slremy <notifications@github.com>
发送时间: 2018年5月8日 13:30
收件人: brightmart/text_classification
抄送: Subscribed
主题: [brightmart/text_classification] License? (#52)


I'm guessing that this code is intended to be open sourced otherwise it wouldn't be here, but is there a particular license that you'd like to choose for your work?

―
