### ISSUE TITLE
ModuleNotFoundError: No module named 'data_util_zhihu'

### ISSUE THREAD

**Issue by dapsjj** [brightmart/text_classification#59]
I use a03_TextRNN,but these two lines has error:
```
from data_util_zhihu import load_data_multilabel_new,create_voabulary,create_voabulary_label
from tflearn.data_utils import pad_sequences #to_categorical

```
The error message said:
```
Traceback (most recent call last):
  File "E:/test_opencv/text_classification-master/a03_TextRNN/p8_TextRNN_train.py", line 10, in <module>
    from data_util_zhihu import load_data_multilabel_new,create_voabulary,create_voabulary_label
ModuleNotFoundError: No module named 'data_util_zhihu'
```

**Comment by brightmart** [comment]
hi,


check TextCNN, there is a file named data_util.py it has two function:

one is create vocabulary for words and labels, another is transform data into indices using vocabulary dict.


bright


________________________________
发件人: Rhaegal <notifications@github.com>
发送时间: 2018年6月1日 14:55
收件人: brightmart/text_classification
抄送: Subscribed
主题: [brightmart/text_classification] ModuleNotFoundError: No module named 'data_util_zhihu' (#59)


I use a03_TextRNN,but these two line:

from data_util_zhihu import load_data_multilabel_new,create_voabulary,create_voabulary_label
from tflearn.data_utils import pad_sequences #to_categorical



The error message said:

Traceback (most recent call last):
  File "E:/test_opencv/text_classification-master/a03_TextRNN/p8_TextRNN_train.py", line 10, in <module>
    from data_util_zhihu import load_data_multilabel_new,create_voabulary,create_voabulary_label
ModuleNotFoundError: No module named 'data_util_zhihu'


―

**Comment by peterHeuz** [comment]
I have the same error.

I corrected 

`from data_util_zhihu import load_data_multilabel_new,create_voabulary,create_voabulary_label
from tflearn.data_utils import pad_sequences #to_categorical`

to

`from a02_TextCNN.data_util import load_data_multilabel, create_vocabulary, \
    create_voabulary_label
from tflearn.data_utils import pad_sequences  # to_cate`

Now it crashes later with:

`ImportError: No module named tflearn.data_utils`

Where can we find `create_voabulary_label` and `tflearn.data_utils` ?

**Comment by f20500909** [comment]
```
ImportError: No module named tflearn.data_utils
```

tflearn is a Python package
use pip install tflearn to slove  it

you can  find create_voabulary_label from https://github.com/brightmart/text_classification/blob/master/a02_TextCNN/other_experiement/data_util_zhihu.py

you can copy /a02_TextCNN/other_experiement/data_util_zhihu.py  to your catalog

**Comment by peterHeuz** [comment]
Great thanks @f20500909 ! I also found out that tflearn is a package, but did not look in the other_experiement folder.

Now it runs further but crashes when executing `create_voabulary`:
`No such file or directory: 'zhihu-word2vec.bin-100'`

Is there additional data that I need, besides cloning the repo? I do not see anything in the documentation, but I assume so since the create_voabulary function has a comment saying `#use pretrained word embedding to get word vocabulary and labels, and its relationship with index`.

**Comment by brightmart** [comment]
you can set flag of use pertained word embedding to false, so it will not use *.bin-100 file.


________________________________
发件人: Peter Heuz <notifications@github.com>
发送时间: 2018年7月26日 18:49
收件人: brightmart/text_classification
抄送: brightmart; Comment
主题: Re: [brightmart/text_classification] ModuleNotFoundError: No module named 'data_util_zhihu' (#59)


Great thanks @f20500909<https://github.com/f20500909> ! I also found out that tflearn is a package, but did not look in the other_experiement folder.

Now it runs further but crashes when executing create_voabulary:
No such file or directory: 'zhihu-word2vec.bin-100'

Is there additional data that I need, besides cloning the repo? I do not see anything in the documentation, but I assume so since the create_voabulary function has a comment saying #use pretrained word embedding to get word vocabulary and labels, and its relationship with index.

―

**Comment by brightmart** [comment]
great job


________________________________
发件人: Peter Heuz <notifications@github.com>
发送时间: 2018年7月26日 16:58
收件人: brightmart/text_classification
抄送: brightmart; Comment
主题: Re: [brightmart/text_classification] ModuleNotFoundError: No module named 'data_util_zhihu' (#59)


I have the same error.

I corrected

from data_util_zhihu import load_data_multilabel_new,create_voabulary,create_voabulary_label from tflearn.data_utils import pad_sequences #to_categorical

to

from a02_TextCNN.data_util import load_data_multilabel, create_vocabulary, \ create_voabulary_label from tflearn.data_utils import pad_sequences # to_cate

Now it crashes later with:

ImportError: No module named tflearn.data_utils

Where can we find create_voabulary_label and tflearn.data_utils ?

―

**Comment by peterHeuz** [comment]
Thanks for the quick reply!

> you can set flag of use pertained word embedding to false, so it will not use *.bin-100 file.

Where is that flag?

**Comment by peterHeuz** [comment]
No worries, I used google translate and followed your suggestions to run your modification of data_util.py. This vocab_label.pik was created. Still the file `zhihu-word2vec.bin-100` is missing when I run `p8_TextRNN_train.py`:
`IOError: [Errno 2] No such file or directory: 'zhihu-word2vec.bin-100'`

**Comment by f20500909** [comment]
link：https://pan.baidu.com/s/1orPKC0cahrIW0CUvPxts1g
pwd：bguc

include zhihu-word2vec-title-desc.bin-100
maybe helpful

**Comment by advancera** [comment]
文件失效了，请问可以再分享一次吗，非常感谢！ @f20500909

**Comment by peterHeuz** [comment]
Okay, this is error is already discussed in another issue: #3 . I will further continue commenting on this one.

Thanks for your help @f20500909 !

**Comment by brightmart** [comment]
re-generated training/validation/test data, and save as cached file, available to download. check this session in README.md:

 #Sample data: cached file
